/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of H264Decoder.xs. Do not edit this file, edit H264Decoder.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/UAV/Pilot/Video/H264Decoder.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#include "uav.h"

#include <libavcodec/avcodec.h>


#define MY_CXT_KEY "UAV::Pilot::Video::H264Decoder::_guts" XS_VERSION


/* Global Data
 * This won't work if we have many decoder objects open, which means this class will be 
 * effectively a singleton.  Need to store these C structures on a per-object basis.
 */
typedef struct {
    AVCodec *codec;
    AVCodecContext *c;
    int frame_count;
    AVFrame *frame;
    uint8_t inbuf[INBUF_SIZE + FF_INPUT_BUFFER_PADDING_SIZE];
    AVPacket avpkt;
} my_cxt_t;

START_MY_CXT


#line 39 "lib/UAV/Pilot/Video/H264Decoder.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 181 "lib/UAV/Pilot/Video/H264Decoder.c"

XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_get_last_frame_c_obj); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_get_last_frame_c_obj)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
#line 80 "lib/UAV/Pilot/Video/H264Decoder.xs"
        dMY_CXT;
#line 194 "lib/UAV/Pilot/Video/H264Decoder.c"
	SV *	RETVAL;
#line 82 "lib/UAV/Pilot/Video/H264Decoder.xs"
        AVFrame* frame = MY_CXT.frame;
        RETVAL = newSViv( (IV) frame );
#line 199 "lib/UAV/Pilot/Video/H264Decoder.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_get_last_frame_pixels_arrayref); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_get_last_frame_pixels_arrayref)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
#line 91 "lib/UAV/Pilot/Video/H264Decoder.xs"
        dMY_CXT;
#line 218 "lib/UAV/Pilot/Video/H264Decoder.c"
	SV *	RETVAL;
#line 93 "lib/UAV/Pilot/Video/H264Decoder.xs"
        int i;
        SV* tmp_sv;
        AV* decoded_frame_y_av = newAV();
        AV* decoded_frame_u_av = newAV();
        AV* decoded_frame_v_av = newAV();
        AV* decoded_frame_av = newAV();

        // TODO Sloppy repetition.  How best to fix this?  Macro, maybe?
        for( i = 0; i < MY_CXT.frame->linesize[AV_FRAME_DATA_Y_CHANNEL]; i++ ) {
            tmp_sv = newSViv( (IV) MY_CXT.frame->data[AV_FRAME_DATA_Y_CHANNEL][i] );
            av_push( decoded_frame_y_av, tmp_sv );
        }
        for( i = 0; i < MY_CXT.frame->linesize[AV_FRAME_DATA_U_CHANNEL]; i++ ) {
            tmp_sv = newSViv( (IV) MY_CXT.frame->data[AV_FRAME_DATA_U_CHANNEL][i] );
            av_push( decoded_frame_u_av, tmp_sv );
        }
        for( i = 0; i < MY_CXT.frame->linesize[AV_FRAME_DATA_V_CHANNEL]; i++ ) {
            tmp_sv = newSViv( (IV) MY_CXT.frame->data[AV_FRAME_DATA_V_CHANNEL][i] );
            av_push( decoded_frame_v_av, tmp_sv );
        }

        av_push( decoded_frame_av, newRV_inc((SV *) decoded_frame_y_av) );
        av_push( decoded_frame_av, newRV_inc((SV *) decoded_frame_u_av) );
        av_push( decoded_frame_av, newRV_inc((SV *) decoded_frame_v_av) );
        RETVAL = newRV_inc((SV *) decoded_frame_av);
#line 246 "lib/UAV/Pilot/Video/H264Decoder.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_process_h264_frame); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UAV__Pilot__Video__H264Decoder_process_h264_frame)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "self, incoming_frame, width, height, encoded_width, encoded_height");
    {
	SV *	self = ST(0)
;
	SV *	incoming_frame = ST(1)
;
	int	width = (int)SvIV(ST(2))
;
	int	height = (int)SvIV(ST(3))
;
	int	encoded_width = (int)SvIV(ST(4))
;
	int	encoded_height = (int)SvIV(ST(5))
;
#line 131 "lib/UAV/Pilot/Video/H264Decoder.xs"
        dMY_CXT;
#line 275 "lib/UAV/Pilot/Video/H264Decoder.c"
	int	RETVAL;
	dXSTARG;
#line 133 "lib/UAV/Pilot/Video/H264Decoder.xs"
        int len, got_frame, i;
        SV** tmp_sv_star;
        AV* incoming_frame_av = (AV*) SvRV(incoming_frame);
        I32 incoming_frame_length = av_len( incoming_frame_av ) + 1;
        AVPacket avpkt = MY_CXT.avpkt;

        uint8_t *pkt_data = malloc( incoming_frame_length * sizeof(uint8_t) );
        if( NULL == pkt_data ) {
            THROW_XS_ERROR( "Could not allocate memory for packet data" );
        }

        for( i = 0; i < incoming_frame_length; i++ ) {
            tmp_sv_star = av_fetch( incoming_frame_av, i, 0 );
            pkt_data[i] = (uint8_t) SvIV( *tmp_sv_star );
        }

        avpkt.data             = pkt_data;
        avpkt.size             = incoming_frame_length;
        MY_CXT.c->width        = width;
        MY_CXT.c->height       = height;
        MY_CXT.c->coded_width  = encoded_width;
        MY_CXT.c->coded_height = encoded_height;

        len = avcodec_decode_video2( MY_CXT.c, MY_CXT.frame, &got_frame, &avpkt );
        free( pkt_data );
        pkt_data = NULL;
        if( len < 0 ) {
            THROW_XS_ERROR( "Error decoding frame" );
        }

        MY_CXT.frame_count++;

        /* Call $self->_iterate_displays() */
        dSP;
        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs( self );
        XPUSHs( sv_2mortal(newSViv(MY_CXT.frame->width)) );
        XPUSHs( sv_2mortal(newSViv(MY_CXT.frame->height)) );
        PUTBACK;
        call_method( "_iterate_displays", G_DISCARD );

        FREETMPS;
        LEAVE;

        /* Yay, everything worked! */
        RETVAL = 1;
#line 328 "lib/UAV/Pilot/Video/H264Decoder.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_UAV__Pilot__Video__H264Decoder); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_UAV__Pilot__Video__H264Decoder)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("UAV::Pilot::Video::H264Decoder::get_last_frame_c_obj", XS_UAV__Pilot__Video__H264Decoder_get_last_frame_c_obj, file);
        newXS("UAV::Pilot::Video::H264Decoder::get_last_frame_pixels_arrayref", XS_UAV__Pilot__Video__H264Decoder_get_last_frame_pixels_arrayref, file);
        newXS("UAV::Pilot::Video::H264Decoder::process_h264_frame", XS_UAV__Pilot__Video__H264Decoder_process_h264_frame, file);

    /* Initialisation Section */

#line 32 "lib/UAV/Pilot/Video/H264Decoder.xs"
{
    MY_CXT_INIT;
    av_init_packet(&MY_CXT.avpkt);
    /* set end of buffer to 0 (this ensures that no overreading happens for damaged mpeg streams) */
    memset(MY_CXT.inbuf + INBUF_SIZE, 0, FF_INPUT_BUFFER_PADDING_SIZE);

    /* find the h264 video decoder */
    avcodec_register_all();
    MY_CXT.codec = avcodec_find_decoder( CODEC_ID );
    if (!MY_CXT.codec) {
        THROW_XS_ERROR( "Codec H264 not found" );
    }

    MY_CXT.c = avcodec_alloc_context3(MY_CXT.codec);
    if (!MY_CXT.c) {
        THROW_XS_ERROR( "Could not allocate video codec context" );
    }
    if(MY_CXT.codec->capabilities&CODEC_CAP_TRUNCATED) {
        MY_CXT.c->flags|= CODEC_FLAG_TRUNCATED; /* we do not send complete frames */
    }
    MY_CXT.c->pix_fmt = UAV_PIX_FMT;
    /* For some codecs, such as msmpeg4 and mpeg4, width and height
    * MUST be initialized there because this information is not
    * available in the bitstream. */
    /* open it */
    if (avcodec_open2(MY_CXT.c, MY_CXT.codec, NULL) < 0) {
        THROW_XS_ERROR( "Could not open codec" );
    }

    MY_CXT.frame = avcodec_alloc_frame();
    if (!MY_CXT.frame) {
        THROW_XS_ERROR( "Could not allocate frame" );
    }
    MY_CXT.frame_count = 0;
}

#line 397 "lib/UAV/Pilot/Video/H264Decoder.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

